# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: AI Reviewer

concurrency:
  group: ai-reviewer-${{ github.head_ref }}
  cancel-in-progress: true
on:
  # trigger the workflow on pr is ready for review
  pull_request:
    branches:
      - master
    # types: [ready_for_review]

jobs:
  ai-reviewer:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install

      - name: Get diff
        id: get-diff
        run: |
          git fetch origin
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          git diff origin/master..HEAD -- '*.ts' | tr -d '\r' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run AI Reviewer
        id: ai-reviewer
        run: bun reviewer.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DIFF: ${{ steps.get-diff.outputs.diff }}

      - name: Process review results
        id: process
        run: |
          content="🤖 AI Reviewer result 🤖\n\n"
          echo "${{ steps.ai-reviewer.outputs.review }}" | jq -r '.[] | "### File: `\(.file)`\n```\n\(.fixedCode)\n```\n"' >> comment.txt

      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        if: ${{ steps.ai-reviewer.outputs.review != 'NO_ISSUES' }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body-path: comment.txt
