# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: AI Reviewer

concurrency:
  group: ai-reviewer-${{ github.head_ref }}
  cancel-in-progress: true
on:
  # trigger the workflow on pr is ready for review
  pull_request:
    branches:
      - master
    # types: [ready_for_review]

jobs:
  ai-reviewer:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install

      - name: Get diff
        id: get-diff
        run: |
          echo "diff=$(git diff master..${GITHUB_REF#refs/heads/} -- '*.ts')" >> $GITHUB_OUTPUT

      - name: Run AI Reviewer
        id: ai-reviewer
        run: bun reviewer.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DIFF: ${{ steps.get-diff.outputs.diff }}

      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            :robot: AI Reviewer result :robot:
            ${{ steps.ai-reviewer.outputs.review }}
